version: "3.8"

services:
  mongo:
    image: mongo:7.0.12
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api: 
    build: 
      context: ./be
      target: development
    restart: "unless-stopped"
    env_file: ./be/.env
    volumes:
      - ./be:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend: 
   build:
    context: ./fe
    target: development
    args:
     VITE_API_URL: https://api.auth.localhost
   restart: "unless-stopped"
   env_file: "./fe/.env"
   volumes:
     - ./fe:/app
     - /app/node_modules
   networks: 
     - mern-app
   ports: 
     - 5173:5173
   command: npm run dev -- --host

   depends_on:
      - api

  caddy: 
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - mern-app
    depends_on:
      - frontend
      - api

volumes:
  mongo_data:

networks:
  mern-app: 
    driver: bridge
